# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [4]:
# Given:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

# Expected Output:
# Given list: [10, 20, 30, 40, 10]
# result is True

# numbers_y = [75, 65, 35, 75, 30]
# result is False
def same(arr):
    return arr[0]==arr[-1]
print(same(numbers_x))
print(same(numbers_y))

True
False






# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [108]:
import numpy as np
#code here
arr1  = np.array([[1,2,3],
        [4,5,6],
         [7,8,9]])
arr2  = np.array([[11,12,13],
        [14,15,16],
         [17,18,19]])

arr1+arr2
arr1*arr2

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [15]:
#code here
arr_1d= [1,2,3,4,5,6,7,8,9,10,11,12]
arr_1d= np.array(arr_1d)
arr1 = arr_1d.reshape(3,4)

arr_1d= [11,12,13,14,15,16,17,18,19,20,21,22]
arr_1d= np.array(arr_1d)
arr2 = arr_1d.reshape(3,4)

print(np.concatenate((arr1,arr2,),axis=0))
print("**********************************")
print(np.concatenate((arr1,arr2,),axis=1))



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
**********************************
[[ 1  2  3  4 11 12 13 14]
 [ 5  6  7  8 15 16 17 18]
 [ 9 10 11 12 19 20 21 22]]


# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [109]:
#Code here
shopping_cart = []
print("WELCOME TO cKart")
items=["Mouse","Keyboard","Lcd","Ram","SSD","HDD","Cables","Chair","PC TABLE"]
dic={}
count=1
for i in items:
    dic[count] = i
    count+=1
n=True
print("0: To exit")
for k,i in dic.items():
        print(k,i)
while n:
   
    n= int(input("ADD ITEM TO CART"))
    if n==0:
        break
    shopping_cart.append(dic[n])
    print("item added")
    print(shopping_cart)
    
print("GOODBYE AND THANKS FOR JOINING cKart")

WELCOME TO cKart
0: To exit
1 Mouse
2 Keyboard
3 Lcd
4 Ram
5 SSD
6 HDD
7 Cables
8 Chair
9 PC TABLE
ADD ITEM TO CART1
item added
['Mouse']
ADD ITEM TO CART2
item added
['Mouse', 'Keyboard']
ADD ITEM TO CART3
item added
['Mouse', 'Keyboard', 'Lcd']
ADD ITEM TO CART0
GOODBYE AND THANKS FOR JOINING cKart


# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [52]:
#code here

def classify(emails):
    impp=[]
    promo=[]
    spam=[]
    for e in emails:
        print(e)
        if 'important' in e:
            impp.append(e)
        elif 'promotion' in e:
            promo.append(e)
        elif 'spam' in e:
            spam.append(e)
            
    return impp, promo, spam

Email = [
    'This is a very important email. Please respond to it as soon as possible',
    'This is a spam email',
    'This email is for promotion purpose',
    'This is a spam promotion spam email',
]

impp, promo, spam = classify(Email)

print('Important Emails are: ')
print(impp)
print()
print('Promotional Emails are: ')
print(promo)
print()
print('Spam Emails are: ')
print(spam)

This is a very important email. Please respond to it as soon as possible
This is a spam email
This email is for promotion purpose
This is a spam promotion spam email
Important Emails are: 
['This is a very important email. Please respond to it as soon as possible']

Promotional Emails are: 
['This email is for promotion purpose', 'This is a spam promotion spam email']

Spam Emails are: 
['This is a spam email']


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [56]:
#code here
english_to_spanish = {
    "hello": "hola",
    "goodbye": "adiós",
    "thank you": "gracias",
    "please": "por favor",
    "yes": "sí",
    "no": "no",
}
print("press q to exit")
on = True
while on:

    c = input("enter a english word")
    if c =='q':
        on=False
        break
    try:
        print(english_to_spanish[c])
    except:
        print("translation is not available.")
    
    



press q to exit
enter a english wordhello
hola
enter a english wordyes
sí
enter a english wordno
no
enter a english wordnow
translation is not available.
enter a english wordq


# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [62]:
import pandas as pd

In [64]:
link ="https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv"
df = pd.read_csv(link)

In [69]:
df.head()

Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37

In [67]:
g1 = df["Global_Sales"].sum()
print("total global sales : ",g1 )

total global sales :  8920.44


In [68]:
h1 = df["Global_Sales"].max()
print("highest global sales : ",h1 )

highest global sales :  82.74


In [75]:
df.loc[:,"NA_Sales":"Other_Sales"].mean()

NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64

In [80]:
popular = df.sort_values(by='Global_Sales',ascending=False)

In [82]:
popular.head(5)

Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37

In [100]:
#Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales)
genre = df.groupby(by="Genre")
region=genre[["NA_Sales","EU_Sales","JP_Sales","Other_Sales"]].sum()
region

NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36

In [102]:
region["NA_Sales"].idxmax()

'Action'

In [83]:
#Display last 10 rows.
df.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [84]:
# Determine the top 3 gaming platforms with the highest global sales.
popular.head(3)["Platform"]

0    Wii
1    NES
2    Wii
Name: Platform, dtype: object

In [106]:
#Determine the top 3 gaming platforms with the highest global sales
(genre["Global_Sales"].sum()/g1)*100

Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64

In [107]:
# Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)
df["NA_Sales"].corr(df["EU_Sales"])

0.7677267483702636